### ISSUE TITLE
Események egyedi dátummal

### ISSUE THREAD

**Issue by molnarm** [molnarm/liturgia.tv#16]
Karácsony, Újév, Vízkereszt stb., egyedi alkalmak

**Comment by borazslo** [comment]
Különösen is szent három nap + húsvét. 

- Lehetne külön adatbeviteli formot csinálni húsvétra, hogy minél könnyebb legyen az adatgyűjtés.
- Akár önkénteseket is be lehet vonni, akik rátelefonálnak helyekre, hogy tényleg úgy van-e, vagy ellenőriznek, vagy bármi. Tudok ebben segíteni és biztosan van megoldás.

(Meg ha másban kell segítség, hátha tudok segíteni ...)

**Comment by molnarm** [comment]
Igen, ez is kell húsvétra, van pár dolog, amit addig még megcsinálok. 

Az adatgyűjtés tényleg béna, csinálok majd egyszerűbbet.

Az önkéntesek tök jók lennének, az adatgyűjtés/kezelésre most nincs sok időm (ezt itt nem fejteném ki :D)
Az ellenőrzés is hasznos, de ugyanígy jól jönne az új közvetítések begyűjtése is (ez főleg most aktuális), meg ha megkeresné valaki azokat a helyeket, ahol le van tiltva a youtube beágyazás.

Ha vannak megbízható emberek, szívesen adok jogosultságokat az adatok szerkesztéséhez, most kicsit kipofoztam az admin felületet, hogy érthetőbb legyen. És ha van rá ember, jöhetnek a protestáns közvetítések is (#17).

**Comment by molnarm** [comment]
Majd leírom, hogy hogy működik, de lehet, hogy csak a #46 után.
