### ISSUE TITLE
Saját domain?

### ISSUE THREAD

**Issue by molnarm** [molnarm/liturgia.tv#17]
Valami cím, amit könnyű megjegyezni és jobban tükrözi a tartalmat?
Magyar domaint tudtommal még mindig csak tanúztatva lehet igényelni, úgyhogy ezt én nem tudom most megoldani.

**Comment by borazslo** [comment]
Nem jut jó az eszembe, de ilyesmin indulnék:
- liturgia (hiszen több mint zsolozsma, szentmise, szent liturgia)
- közvetítések (nem pedig "élő", mert nem is abban az értelemben)
- csak katolikus egyébként? akkor ez is ki kéne belőle derüljön

kozvetitesek.katolikus.hu :D -» Persze kell hozzá engedély valahonnan felülről de csak lehet velük beszélni
kozvetites.miserend.hu -» Könnyen megoldható. :D 

digitalisliturgiak.hu

**Comment by molnarm** [comment]
Köszi az ötletelést :-) Nem is tudom igazából, hogy mennyire lenne fontos ez még, mennyi közvetítés lesz az aktuális járvány-hullám után és/vagy mekkora igény lenne rájuk...

Nem kell feltétlenül csak katolikusnak lennie az oldalnak, részben ezért is lett benne felekezet/rítus szerinti szűrés, de arra végképp nem volt kapacitásom, hogy nekiálljak begyűjteni a protestáns közvetítéseket is. (Ilyesmikben látszanak az ilyen önkéntes hiánypótló munkák korlátai.)

Nem rosszak ezek az aldomainek sem, bár egyrészt kicsit félnék nagyon "hivatalosnak" feltüntetni a dolgot, másrészt nem tudom, mennyire lenne könnyű megjegyezni őket. Átirányításnak persze bármikor felvehetik őket a webmesterek.

`liturgia.tv`?

**Comment by borazslo** [comment]
A `liturgia.tv` igazából tényleg könnyen megjegyezhető és kifejezi azt ami. Persze én kicsit mindig gyanúsan néz(t)em a `.tv`-s domaineket. A `digitalisliturgia.hu` ezért kicsit jobban bejön.

Szerintem meg fog maradni egy csökkentett de állandó valós igény ezekre. Ezért is köszi a miserend öszeköttetést. A járvány végefelé majd rengeteg rengeteg adatot kell majd mindenütt frissítenünk.
