### ISSUE TITLE
Szöveg a misékhez

### ISSUE THREAD

**Issue by molnarm** [molnarm/liturgia.tv#19]
adoremus? igenaptár mint miseszöveg? van valami jobb online?

**Comment by molnarm** [comment]
Az állandó szövegeket megtaláltam, talán ezek fontosabbak a közvetítés mellé a liturgia követéséhez, mint az olvasmányok (amik amúgy megvannak az igenaptar.katolikus.hu-n)

**Comment by molnarm** [comment]
Jó lenne valami külön is felhasználható aloldal, ami a mise [állandó szövegeit](https://www.liturgia.hu/a-szentmise-menete/) meg a [változó részeke](https://igenaptar.katolikus.hu/)t összevasalja, és beágyazható.

**Comment by borazslo** [comment]
oh, de szép is lenne a digitális zsolozsmához hasonló digitális misekönyv. Oh, http://misekonyv.hu . Kár hogy sehogy nem áll évek óta a projekt.
