### ISSUE TITLE
Facebook live

### ISSUE THREAD

**Issue by borazslo** [molnarm/liturgia.tv#3]
Jól értem, hogy csak youtube-os közvetítésekkel működik? Egyrészt teljesen érthető, de azért nyitok egy ilyet, hátha van remény.

Ha meg nincs, akkor majd propagálom pár helyen, hogy térjenek át youtube-ra, vagy egyszerre a kettőre.

**Comment by borazslo** [comment]
Olyat sikerült nekem csinálnom a facebook API-n keresztül. hogy ha egy facebook oldalhoz hozzá voltam adva bizonyos jogkörökkel én (vagy a development fázisban lévő appom?), akkor API-n keresztül le tudtam kérdezni a futó lájvokat és linkjét és beágyazását is ilyenek. (Indítani bonyolultabb sokkal sajna.) Szerintem lehet egy ilyen félig nem létező facebook személyt létrehozni, akit hozzá lehet adni a rendszeresen közvetítő oldalakhoz és akkor mehet a beágyazás a gyűjteménybe.

**Comment by molnarm** [comment]
Bármivel működik, csak a youtube beágyazás külön van kezelve, hogy jó legyen, mert abból van a legtöbb.

Több helyről is hallottam egyébként azt a tapasztalatot, hogy a youtube-os közvetítés megbízhatóbb és jobb minőségű, mint facebookon (utoljára Bakonybélből és a quiznight.hu-tól). Plusz a youtube-ot telefonon vagy okosTV-n is könnyebb nézni. Szóval nem csak emiatt érdemes propagálni a váltást :-)

Igen, a facebookról normálisan beágyazni csak minden oldalról külön engedélyekkel lehet, tavasszal úgy gondoltam, hogy nem éri meg a befektetett energiát, azóta meg arányaiban még kevesebb van belőle.

**Comment by molnarm** [comment]
Megint van jópár facebookos közvetítés. Arányaiban most is jóval kevesebb, mint a youtube, de azért lehet, hogy mégis foglalkozni kell vele.

**Comment by borazslo** [comment]
A legjobbnak az tűnne, ha készítünk egy facebok app-ot, ami a facebook webhookot használja, így nem lekérdezni kell, hanem kapjuk az értesítést, amikor egy live indul vagy véget ér.

Az emberünk rákattinta az "összekötés facebook"-al gombra. Így szokott facebook app felületen engedélyezi az alkalmazást. Majd megadja, hogy az általa kezelt oldalak közül (amelyik ő az admin vagy minimum moderátor) melyiket kövessük. Mi még küldünk a háttérben a facebookra egy subscribe-ot és megy id a dolog.

Baj csak az, hogy ez csak és kizárólag review-olt facebook app-okkal műköüdik. Különben csak teszt adatokkal lehet tesztelni. (Elekzdtem vele játszani php alapon.)

(( Egyébként tényleg minden szemontból jobb a youtube. Csak ott van egy 1000 feliratkozós beugró a telefonos közvetítéshez. ))

**Comment by molnarm** [comment]
Firefoxban nem fog működni:
https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop
https://bugzilla.mozilla.org/show_bug.cgi?id=1226498

**Comment by molnarm** [comment]
Végül beraktam, mert sokkal jobb lesz tőle a felhasználóknak.
Aki külön beállítja a ["szigorú" követés elleni védelmet](https://support.mozilla.org/hu/kb/tovabbfejlesztett-kovetes-elleni-vedelem-az-asztal#w_szigoru-tovabbfejlesztett-kovetes-elleni-vedelem) (mint én :D ), remélhetőleg azt is tudja, hogy lehet az oldalon kikapcsolni. Vagy megnyitja a facebookot külön lapon.
