### ISSUE TITLE
Szövegek az oldalon

### ISSUE THREAD

**Issue by molnarm** [molnarm/liturgia.tv#30]
A szertartások általános szövegei (vö. #19, #20) legyenek az oldal részei, ne béna felugró ablakban jelenjenek meg valami más oldalról.

**Comment by molnarm** [comment]
A kód kész van hozzá, jöhetnek a szövegek:
- [x] [mise](https://liturgia.tv/szoveg/szentmise/)
- [ ] szent liturgia
- [ ] utrenye
- [ ] vecsernye
- [ ] nagycsütörtök
- [ ] nagypéntek
- [ ] nagyszombat

**Comment by borazslo** [comment]
Húsvéti vigília (azaz nagyszombat) pdf: https://regi.katolikus.hu/csatolt/husvet_vigilia.pdf
